### ISSUE TITLE
ユーザー詳細ページ/ マイページ

### ISSUE THREAD

**Issue by tmkimunida6** [tmkimunida6/bon-voyage-collection#19]
### Tasks
- [ ] ユーザー詳細ページの作成
- [x] マイページの作成
- [ ] ユーザー詳細ページとマイページのコンテンツ出しわけ
- [x] 投稿したお土産、お気に入りに保存したお土産がタブ分けされて表示される
- [ ] 投稿したお土産には「自分の評価」「コメント数」「いいね数」「自分のアップロードした画像」が表示される
- [ ] お気に入りに保存したお土産は「平均評価」「全体の投稿数」「全体のお気に入り数」「お土産詳細ページの画像」が表示される
- [x] 投稿数が表示される（UI要検討）

### Goal
- [ ] ユーザー詳細ページにアクセスができる
- [ ] ユーザー詳細ページ、マイページ共に、投稿したお土産、お気に入りに登録したお土産、絞り込み機能、投稿数が表示されている
- [ ] ユーザー詳細ページにのみ、フォロー中かどうかの目印がある
- [ ] マイページにのみ、設定へのリンクがある
