### ISSUE TITLE
投稿機能

### ISSUE THREAD

**Issue by tmkimunida6** [tmkimunida6/bon-voyage-collection#20]
### Tasks
- [x] 投稿ページの作成
- [x] お土産検索機能（機能実装自体は別タスクにて対応）
- [x] モーダルの実装（[コンポーネント開発](https://github.com/tmkimunida6/new_portfolio/issues/8)で実装済みなので配置のみを想定）
- [x] アコーディオンの実装（[コンポーネント開発](https://github.com/tmkimunida6/new_portfolio/issues/8)で実装済みなので配置のみを想定）

### Goal
- [x] 投稿ができる
- [x] 投稿した内容が一覧に表示される
- [ ] 施設検索、通貨の選択、タグ機能は一旦入力欄だけ（別タスクにて対応）
- [ ] 画像のアップロードは別タスクにで実装
- [ ] 投稿の編集ができる
